name: k8s api deprecation
description: k8s api check comparing based on generated helm template

inputs:
  chartName:
    description: "Helm chart path"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        # Helm 3 installation
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 2>/dev/null | bash >/dev/null
      shell: bash
    - run: |
        # Kubent installation
        curl https://git.io/install-kubent 2>/dev/null | bash >/dev/null
      shell: bash
    - run: |
        # Generate chart template and check apis using kubent
        helm template ${{ inputs.chartName }} | kubent --helm3=false --cluster=false --filename=- 
      shell: bash

branding:
  icon: file-text
  color: white
